Milestone 2
El-Potato-Slayer/Bookstore pull request #2
Opened 2021-08-03 13:24 UTC by El-Potato-Slayer

- Created components directory that holds presentational components
- Created containers directory that holds container components
- Created an action directory that contains all redux actions
- Created reducers directory 
- Implemented BooksList, Book, BooksForm components
- Defined books.js reducer with CREATE_BOOK and REMOVE_BOOK actions
- Initialized redux store

2021-08-03 15:57 UTC, bellom requested changes
## Hi Team :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**Kindly check my comments under this review;**

**Heads-Up:** _Let's make sure to read the instructions on pathwright carefully before submitting CRR, that way, you will have a high chance of getting your CRR reviewed just once without submitting it for re-review or having just a few comments on the PR, my comments seem full over the PR huh, I trust you guys can fix it all 😄 _

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best**

2021-08-03 15:57 UTC, bellom commented on src/components/Book.js
> +// eslint-disable-next-line react/prop-types
With the ESLint inline comment, you are indirectly changing the linter's rules by disabling these rules, let's fix the codebase instead.

Let's add [`typechecking props`](https://reactjs.org/docs/typechecking-with-proptypes.html) to solve this, that was the reason why we added [`prop-types`](https://www.npmjs.com/package/prop-types) to `package.json` in milestone 1.

2021-08-03 15:57 UTC, bellom commented on src/components/Book.js
> +  return <div>{book.title}</div>;
We are trying to create a book row, so we should use `tr` tag  and `td` tags.

Let's add `id` and `category` to the book row.

Screenshot from pathwright:

![image](https://user-images.githubusercontent.com/31897434/128042203-faa3b485-b93c-4804-951a-01d08b08e525.png)

![image](https://user-images.githubusercontent.com/31897434/128040174-c9fcd3a2-de8a-4ebf-86be-bc8bd3d262d6.png)

2021-08-03 15:57 UTC, bellom commented on src/containers/BooksList.js
> +/* eslint-disable react/prop-types */
KIndly add [`typechecking props`](https://reactjs.org/docs/typechecking-with-proptypes.html) and remove this inline comment.

2021-08-03 15:57 UTC, bellom commented on src/containers/BooksList.js
> +/* eslint-disable react/destructuring-assignment */
With the ESLint inline comment, you are indirectly changing the linter's rules by disabling these rules, let's fix the codebase instead.

If you are using VSCode, you can delete the inline comment and hover over the error(configure Eslint checks locally). And you will see your options. Click on the more info button that will take you to a GitHub repo where it is explained why you are getting this error. I find this feature very educational. Please, try to learn and implement the necessary rules so you don't have to keep this disabling line on top of each file. I believe you can do this! 💪😇

2021-08-03 15:57 UTC, bellom commented on src/containers/BooksList.js
> +    // eslint-disable-next-line react/jsx-key
With the ESLint inline comment, you are indirectly changing the linter's rules by disabling these rules, let's fix the codebase instead.

2021-08-03 15:57 UTC, bellom commented on src/containers/BooksList.js
> +// eslint-disable-next-line react/prefer-stateless-function
With the ESLint inline comment, you are indirectly changing the linter's rules by disabling these rules, let's fix the codebase instead.

If you are using VSCode, you can delete the inline comment and hover over the error(configure Eslint checks locally). And you will see your options. Click on the more info button that will take you to a GitHub repo where it is explained why you are getting this error. I find this feature very educational. Please, try to learn and implement the necessary rules so you don't have to keep this disabling line on top of each file. I believe you can do this! 💪😇

Hint: You could use a functional react component.

2021-08-03 15:57 UTC, bellom commented on src/containers/BooksList.js
> +}
let's create a table for the book.
Example:
`thead` for the header, such as: `id`, `title` and `category`
`tbody` tag to display the list of books.

![image](https://user-images.githubusercontent.com/31897434/128045218-23953d64-1eb7-47fb-98eb-90de4aefd8fb.png)

2021-08-03 15:57 UTC, bellom commented on src/store/actions/index.js
> +// eslint-disable-next-line import/prefer-default-export
With the ESLint inline comment, you are indirectly changing the linter's rules by disabling these rules, let's fix the codebase instead.

If you are using VSCode, you can delete the inline comment and hover over the error(configure Eslint checks locally). And you will see your options. Click on the more info button that will take you to a GitHub repo where it is explained why you are getting this error. I find this feature very educational. Please, try to learn and implement the necessary rules so you don't have to keep this disabling line on top of each file. I believe you can do this! 💪😇

2021-08-03 15:57 UTC, bellom commented on src/store/reducers/booksReducer.js
> +];
Let's initialize the redux store in `src/index.js` as stated in the pathwright, which is the best practice.

So simply move this `initialState` to the correct file.

![image](https://user-images.githubusercontent.com/31897434/128045849-c2eed712-d5cc-4ba8-8386-fa618a7fd8dd.png)



Additional Optional way of doing this:

2021-08-03 15:57 UTC, bellom commented on src/store/reducers/booksReducer.js
> +    uniqueId: Date.now() + 1,
### [Optional]
Kindly be aware that you can use uuidv4 to automatically generate ids. read more 👉 [npm uuid](https://www.npmjs.com/package/uuidv4)

Example:
```
import uuid from 'uuidv4'
id: uuid(): {title: 'Power', category: 'Action'}
```

2021-08-03 15:57 UTC, bellom commented on src/store/reducers/booksReducer.js
> +    categories: ['1', '2'],
Kindly check the way I created the book up there.

Categories are define in `src/container/Booksform.js`, I think you should use one them instead of `[1, 2]`

2021-08-03 21:45 UTC, bellom commented on src/containers/BooksForm.js
> +        </label>
Let's create a constant to hold the categories as stated in the project instructions.

Then you can map through the constant created.

Example:
```
{constant.map((cat, i) => (
<option key={book.id} value={cat}>
......
```

screenshot from pathwright:
![image](https://user-images.githubusercontent.com/31897434/128090193-ef96d6c0-7067-49da-95f5-0445caa5cf3b.png)

2021-08-04 13:19 UTC, mahmoud717 requested changes
### Changes required ♻️ 

**Hello @El-Potato-Slayer & @MkrtichSargsyan**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] As requested by the last TSE, the initialState object should be implemented in the src/Index.js file, not in the booksReducer.js file. also, you can use UUID for the ids of the initialState entities. 

- [ ] The store must be created in the src/index.js file. 
Here is an example:
```javascript
const INITIAL_STATE = {
  books: [
  {
    id: uuid(),
    title: 'book1',
    category: 'Action',
  },
  {
    id: uuid(),
    title: 'book2',
    category: 'Biography',
  },
  {
    id: uuid(),
    title: 'book3',
    category: 'Horror',
  },
];
}

const store = createStore(rootReducer, INITIAL_STATE);
```

- [ ] after doing the previous two steps, you face an error regarding the store. this is because adding the initial state to the reducer and adding it to the state directly are two different things. For adding it directly to the CreateStore function, the initialState must be an object that contains a key called books, the value of that key should be the array of books that you have. 

Here is an example:


```javascript
const INITIAL_STATE = {
books: [
  {
    id: uuid(),
    title: 'book1',
    category: 'Action',
  },
  {
    id: uuid(),
    title: 'book2',
    category: 'Biography',
  },
  {
    id: uuid(),
    title: 'book3',
    category: 'Horror',
  },
];
}
```

- [ ] Please make use of the uuidv4 package that you installed. 

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

2021-08-04 13:19 UTC, mahmoud717 commented on src/store/reducers/booksReducer.js
>    },
Move this to the src/index.js file.

2021-08-04 15:02 UTC, El-Potato-Slayer commented
@mahmoud717 We are aware that we can use UUID to generate IDs, luckily it's optional, and we won't be implementing it 😊 We refuse to be oppressed :D
The beast of petty arguments has been awoken, and shall now present an overwhelming amount of arguments why each `INITIAL_STATE` should belong to their respective reducers, not in `src/index.js`:
- [Article 1- Splitting Reducers section](https://redux.js.org/tutorials/fundamentals/part-3-state-actions-reducers)
- [Article 2](https://redux.js.org/style-guide/style-guide#reducers-should-own-the-state-shape)
- [Article 3](https://www.nbcnews.com/mach/science/why-men-won-t-be-getting-pregnant-anytime-soon-ncna820471)
- [Article 4](https://docs.google.com/document/d/1kYn06WF2DLt202-laRfGLtcgcyiXmCZ1J-Zdw78ni0s/edit)
- [Article 5](https://www.mayoclinic.org/healthy-lifestyle/tween-and-teen-health/in-depth/teen-drug-abuse/art-20045921)
- [Article 6](https://www.healthline.com/health/how-many-times-should-you-poop-a-day)
- [Article 7](https://www.nationsonline.org/oneworld/third_world.htm)
- [Article 8](https://redux.js.org/tutorials/fundamentals/part-3-state-actions-reducers)
- [Article 9](https://redux.js.org/style-guide/style-guide#reducers-should-own-the-state-shape)
- [Article 10](https://www.nbcnews.com/mach/science/why-men-won-t-be-getting-pregnant-anytime-soon-ncna820471)
- [Article 11](https://docs.google.com/document/d/1kYn06WF2DLt202-laRfGLtcgcyiXmCZ1J-Zdw78ni0s/edit)
- [Article 12](https://www.mayoclinic.org/healthy-lifestyle/tween-and-teen-health/in-depth/teen-drug-abuse/art-20045921)
- [Article 13](https://www.healthline.com/health/how-many-times-should-you-poop-a-day)
- [Article 14](https://www.nationsonline.org/oneworld/third_world.htm)
- [Article 15](https://redux.js.org/tutorials/fundamentals/part-3-state-actions-reducers)
- [Article 16](https://redux.js.org/style-guide/style-guide#reducers-should-own-the-state-shape)
- [Article 17](https://www.nbcnews.com/mach/science/why-men-won-t-be-getting-pregnant-anytime-soon-ncna820471)
- [Article 18](https://docs.google.com/document/d/1kYn06WF2DLt202-laRfGLtcgcyiXmCZ1J-Zdw78ni0s/edit)
- [Article 19](https://www.mayoclinic.org/healthy-lifestyle/tween-and-teen-health/in-depth/teen-drug-abuse/art-20045921)
- [Article 20](https://www.healthline.com/health/how-many-times-should-you-poop-a-day)
- [Article 21](https://www.nationsonline.org/oneworld/third_world.htm)
- [Article 22](https://redux.js.org/tutorials/fundamentals/part-3-state-actions-reducers)
- [Article 23](https://redux.js.org/style-guide/style-guide#reducers-should-own-the-state-shape)
- [Article 23](https://www.nbcnews.com/mach/science/why-men-won-t-be-getting-pregnant-anytime-soon-ncna820471)
- [Article 24](https://docs.google.com/document/d/1kYn06WF2DLt202-laRfGLtcgcyiXmCZ1J-Zdw78ni0s/edit)
- [Article 25](https://www.mayoclinic.org/healthy-lifestyle/tween-and-teen-health/in-depth/teen-drug-abuse/art-20045921)
- [Article 26](https://www.healthline.com/health/how-many-times-should-you-poop-a-day)
- [Article 27](https://www.nationsonline.org/oneworld/third_world.htm)
- [Article 28](https://redux.js.org/tutorials/fundamentals/part-3-state-actions-reducers)
- [Article 29](https://redux.js.org/style-guide/style-guide#reducers-should-own-the-state-shape)
- [Article 30](https://www.nbcnews.com/mach/science/why-men-won-t-be-getting-pregnant-anytime-soon-ncna820471)
- [Article 31](https://docs.google.com/document/d/1kYn06WF2DLt202-laRfGLtcgcyiXmCZ1J-Zdw78ni0s/edit)
- [Article 32](https://www.mayoclinic.org/healthy-lifestyle/tween-and-teen-health/in-depth/teen-drug-abuse/art-20045921)
- [Article 33](https://www.healthline.com/health/how-many-times-should-you-poop-a-day)
- [Article 34](https://www.nationsonline.org/oneworld/third_world.htm)
- [Article 35](https://redux.js.org/tutorials/fundamentals/part-3-state-actions-reducers)
- [Article 36](https://redux.js.org/style-guide/style-guide#reducers-should-own-the-state-shape)
- [Article 37](https://www.nbcnews.com/mach/science/why-men-won-t-be-getting-pregnant-anytime-soon-ncna820471)
- [Article 38](https://docs.google.com/document/d/1kYn06WF2DLt202-laRfGLtcgcyiXmCZ1J-Zdw78ni0s/edit)
- [Article 39](https://www.mayoclinic.org/healthy-lifestyle/tween-and-teen-health/in-depth/teen-drug-abuse/art-20045921)
- [Article 40](https://www.healthline.com/health/how-many-times-should-you-poop-a-day)
- [Article 41](https://www.nationsonline.org/oneworld/third_world.htm)

2021-08-04 15:08 UTC, mahmoud717 commented
regarding uuid, I'm not telling you it's required. I'm just saying since you already installed the package, why not use it. it's a best practice to only install packages that you are going to use so that you keep your project clean.

regarding the intialState requirement, I'm not making that up, it's a project requirement set by Microverse l, and the milestone will not be approved untill you make it. 

You could have fixed this issue in two minutes instead of trying to make an argument.

2021-08-04 15:17 UTC, mahmoud717 commented
![Capdture](https://user-images.githubusercontent.com/60571499/128206149-82cd1791-da9f-4856-8325-ecf05a754e77.PNG)

2021-08-04 15:18 UTC, El-Potato-Slayer commented
@mahmoud717 You are correct. It may be a requirement, but it's not the best practice. We also got inspired by looking at all the different projects done by TSEs, including yours, and noticed quite a few did it correctly, and still got it approved. Thus our strenuous endeavors will continue :D

"Always take the right path, no matter how hard it may be"
-William Shakespeare

2021-08-04 15:21 UTC, mahmoud717 commented
This is a requirement for the current milestone, not the end product. 
this will change in upcoming milestones. 
this is only to get your project up and running with a store. also so that you are. exposed to all kinds of options. 
if you don't like the requirements, please go ahead and file a ticket for student success.

2021-08-04 15:26 UTC, El-Potato-Slayer commented
@mahmoud717 In that case, you present a very good point, and the decision to change the code to what is required in the milestone will be implemented. 

Thank you for your time. 'Till we meet again :D

2021-08-04 15:42 UTC, mahmoud717 requested changes
### Changes required ♻️ 

**Hello @El-Potato-Slayer & @MkrtichSargsyan**

 You haven't implemented the changes requested in the last review. 
---
### Requested 🔴 

- [ ] Please make sure to implement the changes requested in the previous review 😊😊


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

2021-08-05 09:32 UTC, addod19 requested changes
Hi **TEAM**, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-08-05 09:32 UTC, addod19 commented on src/index.js
- [ ] Yes, you have a point but as explained by the previous code reviewers, we need to follow the guidelines. Guidelines are a way of making sure students follow rules, instructions, etc in their software development career. However, some of the articles you provided to back up your point are irrelevant to the discussion, so let us kindly remove them. It would be better if we address the comment and have a discussion later about it. Sounds good?

2021-08-05 12:00 UTC, El-Potato-Slayer commented
@george-shammar Much appreciated, George 👍

2021-08-05 12:00 UTC, merged